ALTER TABLE Sentences
ADD PRIMARY KEY (Sentence_ID),
ADD FOREIGN KEY (Criminal_ID) REFERENCES Criminals(Criminal_ID),
MODIFY COLUMN Criminal_ID DECIMAL NOT NULL,
ADD FOREIGN KEY (Prob_ID) REFERENCES Prob_officers(Prob_ID),
MODIFY COLUMN Prob_ID DECIMAL NOT NULL
